apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-components.yaml
  - gotk-sync.yaml
patches:
  - patch: |
      apiVersion: source.toolkit.fluxcd.io/v1beta2
      kind: GitRepository
      metadata:
        name: flux-system
        namespace: flux-system
      spec:
        secretRef:
          name: flux-sync
    target:
      kind: GitRepository
      name: flux-system
      namespace: flux-system