---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: before-apps
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./flux/apps/development/before
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

