---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kube-state-metrics
  namespace: flux-system
spec:
  dependsOn:
  - name: before-apps
    namespace: flux-system
  interval: 5m0s
  path: ./flux/apps/development/kube-state-metrics
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

