apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  namespace: flux-system
  name: prometheus-community
spec:
  interval: 30m
  url: https://prometheus-community.github.io/helm-charts
